Style/Documentation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/Not:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SignalException:
  EnforcedStyle: only_raise

Style/TrailingComma:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
