pipelines: 
  - identifier: 'Basic Dump of sqlite3 database to csv' 
    etl:  
      # the following source sqlite3 database should have three tables:
      # games (id, name)
      # levels (id, number)
      # game_levels (game_id, level_id)
      # the data should be retrieved by using following sql:
      # select
      #   g.id, g.names, count(*) as number_of_levels
      # from
      #   game g, levels l, game_levels m
      # where 
      #   g.id = m.game_id AND
      #   l.id = m.level_id
      # group by 
      #   g.id
      - identifier: 'sqlite3_game_level_database'
        name: 'Sqlite3 Game/Level Database'
        type: source
        db_file: 'some_other_path' 
        class: OptimusPrime::Source::Sqlite3
        columns:
          game_id: integer
          game_name: string
          number_of_levels: integer
      - identifier: 'uppercase'    
        name: 'Uppercase Transform'
        type: transform
        class: OptimusPrime::Transform::Uppercase
        in_place_replacement: yes
        sources:
          - 'sqlite3_game_level_database'
            columns: game_name
      - identifier: 'CSV Report'
         name: 'CSV Report'
         type: destination
         file_path: 'report.csv'
         class: OptimusPrime::Destination::CSV
         sources:
           - 'uppercase'
             columns:
                game_id:
                  type: integer
                  label: "Game ID"
                game_name:
                  type: string
                  label: "Game Name"
                number_of_levels: 
                  type: integer
                  label: "Number of Levels"
