test_pipeline:
  graph:
    a:
      class: 'OptimusPrime::Sources::LocalCsv'
      params:
        file_path: '../../spec/supports/csv/local_csv_source_sample.csv'
      next:
        - c
    b:
      class: 'OptimusPrime::Sources::LocalCsv'
      params:
        file_path: '../../spec/supports/csv/local_csv_source_pipe.csv'
        col_sep: '|'
      next:
        - c
    c:
      class: 'OptimusPrime::Destinations::LocalCsv'
      params:
        fields: ['FirstName', 'LastName', 'Title', 'ReportsTo.Email', 'Birthdate', 'Description']
        file_path: '../../spec/supports/csv/destination.csv'
